[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Roberto <rob.ariosa@hotmail.com>"]
edition = "2018"
default-run = "all"

[dependencies]


[[bin]]
name = "all"
path = "src/all.rs"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"